# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 16:36
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180413_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='redis',
            field=models.IntegerField(verbose_name='redis\u914d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='dctuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
